-- =============================================================================
-- RETRACTED. This migration is intentionally a no-op. Do not restore it.
--
-- It was written to reconcile two sticker schemas, before the full picture was
-- known. A third-party review of the web repository showed the reconciliation
-- was both redundant and actively harmful.
--
-- What actually exists in the shared database:
--
--   1. supabase/migrations/20260716000000_telegram_stickers.sql (this repo)
--        sticker_packs(title, cover_url, cover_lottie_url, created_by, is_animated)
--        stickers(emoji, image_url, lottie_url, video_url, thumbnail_url, type)
--        user_sticker_packs, recent_stickers
--
--   2. socialalsamos/supabase/migrations/20260829000500_sticker_system.sql and
--      the migrations that follow it (20260829010000_user_stickers,
--      20260829020000_sticker_pack_sharing, 20260829030000_story_stickers,
--      20260829040000_sticker_trends_moderation)
--        adds slug, name, icon_url, default_kind, source, owner_id, is_premium,
--        is_public, review_status, submitted_at to sticker_packs
--        adds kind, full_url, preview_url, keywords, usage_count, is_public,
--        moderation_status, nsfw_score, nsfw_checked_at, nsfw_labels,
--        created_by to stickers
--        adds sticker_usage_events, sticker_reports, sticker_moderators
--
--   3. socialalsamos/supabase/migrations/20260830162000_sticker_schema_compat.sql
--        already bridges the two namings in both directions, with BEFORE
--        triggers sticker_pack_compat_columns and sticker_compat_columns
--
-- Why the retracted version was harmful:
--
--   - It added a third and fourth BEFORE trigger to sticker_packs and stickers,
--     competing with the compat triggers above. Two triggers mirroring
--     overlapping column sets on the same row is a data-integrity hazard.
--   - It added columns that already exist (slug, is_public, install_count,
--     sticker_count, file_url, thumb_url, width, height).
--   - It created a sticker_usage table, which would have been a third parallel
--     recents mechanism next to recent_stickers and sticker_usage_events.
--   - It set stickers.type to default 'static', unaware that the moderation
--     migration added the constraint stickers_public_requires_nsfw_check
--     (is_public = false or nsfw_checked_at is not null). Inserts that set
--     is_public without a completed NSFW check fail regardless of type.
--
-- The single genuinely missing piece, the touch_sticker_usage entry point that
-- src/lib/stickerRecents.ts calls, now lives in:
--   supabase/migrations/20260831060000_sticker_usage_bridge.sql
-- =============================================================================

select 1;
