BEGIN;

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.reserved_usernames (
  username citext PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('celebrity','brand','short','system','custom')),
  reason text,
  reserved_by uuid REFERENCES public.profiles(id),
  reserved_at timestamptz NOT NULL DEFAULT now(),
  released_to uuid REFERENCES public.profiles(id),
  released_by uuid REFERENCES public.profiles(id),
  released_at timestamptz
);

ALTER TABLE public.reserved_usernames ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read reserved usernames" ON public.reserved_usernames;
CREATE POLICY "Anyone can read reserved usernames"
  ON public.reserved_usernames FOR SELECT
  USING (true);

-- Seed reserved usernames from the curated list (celebrity + brand).
-- The authoritative source is assets/data/reserved_usernames_seed.json.
-- The corporation can extend this at any time via admin_bulk_reserve().
--
-- Insertion is idempotent (ON CONFLICT DO NOTHING) so it's safe to re-run.
-- Handles already-owned handles: if a real Alsamos user already registered
-- one of these names, the INSERT is silently skipped.

INSERT INTO public.reserved_usernames (username, category, reason) VALUES
  -- Celebrity accounts
  ('cristiano', 'celebrity', 'famous_account'),
  ('leomessi', 'celebrity', 'famous_account'),
  ('selenagomez', 'celebrity', 'famous_account'),
  ('therock', 'celebrity', 'famous_account'),
  ('kyliejenner', 'celebrity', 'famous_account'),
  ('arianagrande', 'celebrity', 'famous_account'),
  ('kimkardashian', 'celebrity', 'famous_account'),
  ('beyonce', 'celebrity', 'famous_account'),
  ('khloekardashian', 'celebrity', 'famous_account'),
  ('justinbieber', 'celebrity', 'famous_account'),
  ('kendalljenner', 'celebrity', 'famous_account'),
  ('taylorswift', 'celebrity', 'famous_account'),
  ('virat.kohli', 'celebrity', 'famous_account'),
  ('jlo', 'celebrity', 'famous_account'),
  ('nickiminaj', 'celebrity', 'famous_account'),
  ('kourtneykardash', 'celebrity', 'famous_account'),
  ('mileycyrus', 'celebrity', 'famous_account'),
  ('katyperry', 'celebrity', 'famous_account'),
  ('kevinhart4real', 'celebrity', 'famous_account'),
  ('ddlovato', 'celebrity', 'famous_account'),
  ('neymarjr', 'celebrity', 'famous_account'),
  ('rihanna', 'celebrity', 'famous_account'),
  ('zendaya', 'celebrity', 'famous_account'),
  ('drake', 'celebrity', 'famous_account'),
  ('shakira', 'celebrity', 'famous_account'),
  ('davidbeckham', 'celebrity', 'famous_account'),
  ('ladygaga', 'celebrity', 'famous_account'),
  ('eminem', 'celebrity', 'famous_account'),
  ('kanyewest', 'celebrity', 'famous_account'),
  ('snoopdogg', 'celebrity', 'famous_account'),
  ('travisscott', 'celebrity', 'famous_account'),
  ('billieeilish', 'celebrity', 'famous_account'),
  ('dualipa', 'celebrity', 'famous_account'),
  ('theweeknd', 'celebrity', 'famous_account'),
  ('postmalone', 'celebrity', 'famous_account'),
  ('iamcardib', 'celebrity', 'famous_account'),
  ('oliviarodrigo', 'celebrity', 'famous_account'),
  ('dojacat', 'celebrity', 'famous_account'),
  ('lizzo', 'celebrity', 'famous_account'),
  ('shawnmendes', 'celebrity', 'famous_account'),
  ('camila_cabello', 'celebrity', 'famous_account'),
  ('edsheeran', 'celebrity', 'famous_account'),
  ('brunomars', 'celebrity', 'famous_account'),
  ('kingjames', 'celebrity', 'famous_account'),
  ('stephencurry30', 'celebrity', 'famous_account'),
  ('willsmith', 'celebrity', 'famous_account'),
  ('oprah', 'celebrity', 'famous_account'),
  ('britneyspears', 'celebrity', 'famous_account'),
  ('elonmusk', 'celebrity', 'famous_account'),
  ('barackobama', 'celebrity', 'famous_account'),
  ('khaby.lame', 'celebrity', 'famous_account'),
  ('charlidamelio', 'celebrity', 'famous_account'),
  ('bellapoarch', 'celebrity', 'famous_account'),
  ('addisonre', 'celebrity', 'famous_account'),
  ('zachking', 'celebrity', 'famous_account'),
  ('mrbeast', 'celebrity', 'famous_account'),
  ('pewdiepie', 'celebrity', 'famous_account'),
  ('jungkook', 'celebrity', 'famous_account'),
  ('lalalalisa_m', 'celebrity', 'famous_account'),
  ('vinijr', 'celebrity', 'famous_account'),
  ('badgalriri', 'celebrity', 'famous_account'),
  ('chrisbrownofficial', 'celebrity', 'famous_account'),
  ('vindiesel', 'celebrity', 'famous_account'),
  ('ye', 'celebrity', 'famous_account'),
  ('usainbolt', 'celebrity', 'famous_account'),
  ('sergioramos', 'celebrity', 'famous_account'),
  ('kevindurant', 'celebrity', 'famous_account'),
  ('jimmyfallon', 'celebrity', 'famous_account'),
  ('narendramodi', 'celebrity', 'famous_account'),
  ('realdonaldtrump', 'celebrity', 'famous_account'),
  ('dixiedamelio', 'celebrity', 'famous_account'),
  ('kimberly.loaiza', 'celebrity', 'famous_account'),

  -- Brand / organisation accounts
  ('nike', 'brand', 'famous_account'),
  ('adidas', 'brand', 'famous_account'),
  ('gucci', 'brand', 'famous_account'),
  ('louisvuitton', 'brand', 'famous_account'),
  ('zara', 'brand', 'famous_account'),
  ('hm', 'brand', 'famous_account'),
  ('cocacola', 'brand', 'famous_account'),
  ('pepsi', 'brand', 'famous_account'),
  ('mcdonalds', 'brand', 'famous_account'),
  ('starbucks', 'brand', 'famous_account'),
  ('google', 'brand', 'famous_account'),
  ('apple', 'brand', 'famous_account'),
  ('microsoft', 'brand', 'famous_account'),
  ('amazon', 'brand', 'famous_account'),
  ('samsung', 'brand', 'famous_account'),
  ('tesla', 'brand', 'famous_account'),
  ('netflix', 'brand', 'famous_account'),
  ('spotify', 'brand', 'famous_account'),
  ('youtube', 'brand', 'famous_account'),
  ('facebook', 'brand', 'famous_account'),
  ('meta', 'brand', 'famous_account'),
  ('whatsapp', 'brand', 'famous_account'),
  ('telegram', 'brand', 'famous_account'),
  ('twitter', 'brand', 'famous_account'),
  ('tiktok', 'brand', 'famous_account'),
  ('snapchat', 'brand', 'famous_account'),
  ('playstation', 'brand', 'famous_account'),
  ('xbox', 'brand', 'famous_account'),
  ('nintendo', 'brand', 'famous_account'),
  ('marvel', 'brand', 'famous_account'),
  ('disney', 'brand', 'famous_account'),
  ('pixar', 'brand', 'famous_account'),
  ('nasa', 'brand', 'famous_account'),
  ('natgeo', 'brand', 'famous_account'),
  ('cnn', 'brand', 'famous_account'),
  ('bbc', 'brand', 'famous_account'),
  ('nba', 'brand', 'famous_account'),
  ('nfl', 'brand', 'famous_account'),
  ('fifa', 'brand', 'famous_account'),
  ('realmadrid', 'brand', 'famous_account'),
  ('fcbarcelona', 'brand', 'famous_account'),
  ('manchesterunited', 'brand', 'famous_account'),
  ('formula1', 'brand', 'famous_account'),
  ('ferrari', 'brand', 'famous_account'),
  ('lamborghini', 'brand', 'famous_account'),
  ('bmw', 'brand', 'famous_account'),
  ('mercedesbenz', 'brand', 'famous_account'),
  ('toyota', 'brand', 'famous_account'),
  ('coldplay', 'brand', 'famous_account'),
  ('maroon5', 'brand', 'famous_account'),
  ('imaginedragons', 'brand', 'famous_account'),
  ('chanel', 'brand', 'famous_account'),
  ('victoriassecret', 'brand', 'famous_account'),
  ('hbo', 'brand', 'famous_account'),
  ('wwe', 'brand', 'famous_account'),
  ('spacex', 'brand', 'famous_account'),
  ('uefa', 'brand', 'famous_account'),
  ('championsleague', 'brand', 'famous_account'),
  ('nytimes', 'brand', 'famous_account'),
  ('bts_official', 'brand', 'famous_account'),
  ('blackpinkofficial', 'brand', 'famous_account'),
  ('chanelofficial', 'brand', 'famous_account'),
  ('disneyplus', 'brand', 'famous_account'),
  ('warnerbros', 'brand', 'famous_account'),
  ('tseries', 'brand', 'famous_account'),
  ('cocomelon', 'brand', 'famous_account'),
  ('setindia', 'brand', 'famous_account')
ON CONFLICT (username) DO NOTHING;

COMMIT;

NOTIFY pgrst, 'reload schema';
